### ISSUE TITLE
GUI in Docker

### ISSUE THREAD

**Issue by tlkh** [methylDragon/svo_ros_docker#1]
I was looking through the README and for what it's worth you can run a normal GUI in Docker on a system (irregardless of NVIDIA GPU) the following way. Like for eg. you can run Chrome with something like:

```bash
xhost +    # enables connecting to host X server
docker run --privileged \
 --ipc=host \    # some apps will crash without this e.g. Firefox
 --env="DISPLAY" \
 -v /tmp/.X11-unix:/tmp/.X11-unix \
 docker/docker-img:tag
```

Only if you want proper OpenGL acceleration things get tricky, but again, it's not specifically an issue with NVIDIA GPUs. 

Just FYI.

**Comment by methylDragon** [comment]
Oh, right! I should clarify on the README then. The issue is mainly with the ROS RViz GUI because it uses OpenGL.

:+1:
